### ISSUE TITLE
PEP 541 Request: ifcopenshell

### ISSUE THREAD

**Issue by Moult** [pypa/pypi-support#2197]
### Project to be claimed

`PROJECT_NAME`: https://pypi.org/project/ifcopenshell

### Your PyPI username

`USER_NAME`: https://pypi.org/user/Moult

### Reasons for the request

https://pypi.org/project/ifcopenshell does not exist. I am one of the devs behind https://github.com/ifcopenshell/ifcopenshell looking to provide an official PyPi package. I think there have been a few unofficial attempts such as https://pypi.org/project/python-ifcopenshell/ which is now very outdated.

For now I've published to https://pypi.org/project/ifcopenshell-python but it would be nice to claim https://pypi.org/project/ifcopenshell and use that instead :)

### Maintenance or replacement?

Replacement

### Source code repositories URLs

https://github.com/ifcopenshell/ifcopenshell - only one project I guess?

### Contact and additional research

Not sure who to contact as https://pypi.org/project/ifcopenshell does not exist so not sure which exactly is causing the naming conflict.

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by yeraydiazdiaz** [comment]
Hi @Moult, it seems there is no `ifcopenshell` project and I see no entries regarding such name. You should be able to simply upload your project normally.

**Comment by Moult** [comment]
Not much more information with verbose enabled:

```
$ twine upload --verbose dist/*
Uploading distributions to https://upload.pypi.org/legacy/
INFO     dist/ifcopenshell-0.7.0-221004-py310-none-win_amd64.whl (57.0 MB)                                                                                                                                                                     
INFO     Querying keyring for username                                                                                                                                                                                                         
Enter your username: Moult
INFO     Querying keyring for password                                                                                                                                                                                                         
WARNING  Error getting password from keyring                                                                                                                                                                                                   
         Traceback (most recent call last):                                                                                                                                                                                                    
           File "/home/dion/Projects/env/lib/python3.10/site-packages/twine/auth.py", line 74, in get_password_from_keyring                                                                                                                    
             return cast(str, keyring.get_password(system, username))                                                                                                                                                                          
           File "/home/dion/Projects/env/lib/python3.10/site-packages/keyring/core.py", line 55, in get_password                                                                                                                               
             return get_keyring().get_password(service_name, username)                                                                                                                                                                         
           File "/home/dion/Projects/env/lib/python3.10/site-packages/keyring/backends/fail.py", line 25, in get_password                                                                                                                      
             raise NoKeyringError(msg)                                                                                                                                                                                                         
         keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See                       
         https://pypi.org/project/keyring for details.                                                                                                                                                                                         
Enter your password: 
INFO     username: Moult                                                                                                                                                                                                                       
INFO     password: <hidden>                                                                                                                                                                                                                    
Uploading ifcopenshell-0.7.0-221004-py310-none-win_amd64.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 MB • 00:26 • 2.0 MB/s
INFO     Response from https://upload.pypi.org/legacy/:                                                                                                                                                                                        
         400 The name 'ifcopenshell' isn't allowed. See https://pypi.org/help/#project-name for more information.                                                                                                                              
INFO     <html>                                                                                                                                                                                                                                
          <head>                                                                                                                                                                                                                               
           <title>400 The name 'ifcopenshell' isn't allowed. See https://pypi.org/help/#project-name for more information.</title>                                                                                                             
          </head>                                                                                                                                                                                                                              
          <body>                                                                                                                                                                                                                               
           <h1>400 The name 'ifcopenshell' isn't allowed. See https://pypi.org/help/#project-name for more information.</h1>                                                                                                                   
           The server could not comply with the request since it is either malformed or otherwise incorrect.<br/><br/>                                                                                                                         
         The name &#x27;ifcopenshell&#x27; isn&#x27;t allowed. See https://pypi.org/help/#project-name for more information.                                                                                                                   
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                               
          </body>                                                                                                                                                                                                                              
         </html>                                                                                                                                                                                                                               
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/                                                                                                                                                                       
         The name 'ifcopenshell' isn't allowed. See https://pypi.org/help/#project-name for more information.
```

**Comment by yeraydiazdiaz** [comment]
It seems the project was placed in the prohibited project names list. A @pypa/warehouse-admins should be able to release the project name to you.
