### ISSUE TITLE
TestPyPI search and pip install not working

### ISSUE THREAD

**Issue by Legorooj** [pypa/pypi-support#235]
I'm learning (finally) how to package with pypi. When I upload my package to TestPyPI, it all works fine. The package uploads, I can go the the [project page](https://test.pypi.org/project/gnomon) and it looks fine. I can download the wheels, all fine. It installs, renders etc fine. If I search for `G/gnomon` however nothing comes up. I search for the keywords, the title, etc. If I try to install using the command on the page, it fails with `can't find package matching Gnomon`. 

I've tried everything google, SO, the docs and GitHub have to offer. Maybe I'm missing something, but I don't think so.

What should I do?

**Comment by Legorooj** [comment]
@di no that doesn't change the output at all. And it still doesn't explain why you can't find it on search - unless there is some kind of DB delay in adding packages?

**Comment by hugovk** [comment]
I can see it on search:

![image](https://user-images.githubusercontent.com/1324225/75603680-737a0100-5ad9-11ea-825a-a7faabd105ab.png)

![image](https://user-images.githubusercontent.com/1324225/75603682-7aa10f00-5ad9-11ea-8802-bfde1ed9426f.png)

I can install with Python 2.7:
```console
$ pip2 install -i https://test.pypi.org/simple/ Gnomon
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://test.pypi.org/simple/
Collecting Gnomon
  Downloading https://test-files.pythonhosted.org/packages/2f/6b/5e61a8b1c4c4c225a384287dde7e78714d1434a4b89dfdec602a940e6805/Gnomon-0.1.dev1.tar.gz (2.2 kB)
Requirement already satisfied: tqdm>=4.0 in /usr/local/lib/python2.7/site-packages (from Gnomon) (4.21.0)
Building wheels for collected packages: Gnomon
  Building wheel for Gnomon (setup.py) ... done
  Created wheel for Gnomon: filename=Gnomon-0.1.dev1-py2-none-any.whl size=3425 sha256=5a913a2bdb5a4e1ef21f456dd60458e5b260bdde21661ac326e24cf23f3b80ed
  Stored in directory: /Users/hugo/Library/Caches/pip/wheels/2b/60/e7/db5ce46189ff87c0a134e0bf2140a430ae48bec10d489697df
Successfully built Gnomon
Installing collected packages: Gnomon
Successfully installed Gnomon-0.1.dev1
```

But note it "Requires: Python <=3.5", so I can't with, say, Python 3.8:

```console
$ pip install -i https://test.pypi.org/simple/ Gnomon --verbose
Non-user install because site-packages writeable
Created temporary directory: /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-ephem-wheel-cache-yo6d2di0
Created temporary directory: /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-req-tracker-t2g943ki
Initialized build tracking at /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-req-tracker-t2g943ki
Created build tracker: /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-req-tracker-t2g943ki
Entered build tracker: /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-req-tracker-t2g943ki
Created temporary directory: /private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-install-xkubvmda
Looking in indexes: https://test.pypi.org/simple/
1 location(s) to search for versions of Gnomon:
* https://test.pypi.org/simple/gnomon/
Fetching project page and analyzing links: https://test.pypi.org/simple/gnomon/
Getting page https://test.pypi.org/simple/gnomon/
Found index url https://test.pypi.org/simple/
Getting credentials from keyring for https://test.pypi.org/simple/
Getting credentials from keyring for test.pypi.org
Looking up "https://test.pypi.org/simple/gnomon/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): test.pypi.org:443
https://test.pypi.org:443 "GET /simple/gnomon/ HTTP/1.1" 304 0
  Link requires a different Python (3.8.1 not in: '<=3.5'): https://test-files.pythonhosted.org/packages/0e/76/851623e2fb15e579a09797d97d64df7b33250c2fb6757455b45c4c9f773f/Gnomon-0.1.dev1-py3-none-any.whl#sha256=668cff7d8c083cdf3a74fc3341e10ba8a6d749284dc4e11edef7eb10cfbf41a8 (from https://test.pypi.org/simple/gnomon/) (requires-python:<=3.5)
  Skipping link: unsupported archive format: .egg: https://test-files.pythonhosted.org/packages/d5/c7/e284127153c198aa46649cf3c20f4f21152a7822e8e97eaf18a26a2eade3/Gnomon-0.1.dev1-py3.7.egg#sha256=c5811a4c68ea34621c4b41983a93bdaa7707dbdef409e53626ff1b600de53f35 (from https://test.pypi.org/simple/gnomon/) (requires-python:<=3.5)
  Link requires a different Python (3.8.1 not in: '<=3.5'): https://test-files.pythonhosted.org/packages/2f/6b/5e61a8b1c4c4c225a384287dde7e78714d1434a4b89dfdec602a940e6805/Gnomon-0.1.dev1.tar.gz#sha256=96ad4dde699354382a972f0913ea51e90f86379b222c36b9d8f2fa6fbc6f46cc (from https://test.pypi.org/simple/gnomon/) (requires-python:<=3.5)
Given no hashes to check 0 links for project 'Gnomon': discarding no candidates
ERROR: Could not find a version that satisfies the requirement Gnomon (from versions: none)
Cleaning up...
Removed build tracker: '/private/var/folders/kt/j77sf4_n6fnbx6pg199rbx700000gn/T/pip-req-tracker-t2g943ki'
ERROR: No matching distribution found for Gnomon
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for Gnomon
```

**Comment by Legorooj** [comment]
@hugovk behold the prophet:
> unless there is some kind of DB delay in adding packages?

Thanks for your help guys! I can't believe it was something so simple.

Though @di just to check is this expected in the system? This was well over a 12 hour delay. It wasn't coming up this morning (AEST) and I'd uploaded the packages the previous afternoon.
