### ISSUE TITLE
Cannot install any package with pip 

### ISSUE THREAD

**Issue by daler-rahimov** [pypa/pypi-support#540]
## My Platform

pip version: 
  pip 20.2 from /home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip (python 3.5)

OS is WSL: 
  Distributor ID: Ubuntu
  Description:    Ubuntu 16.04.6 LTS
  Release:        16.04
  Codename:       xenial

PyPi: 
  I can connect to PyPi with a web browser and download any packages 

### DNS Resolution

```shell
dig pypi.org A
; <<>> DiG 9.10.3-P4-Ubuntu <<>> pypi.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 3677
;; flags: qr rd ad; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;pypi.org.                      IN      A

;; ANSWER SECTION:
pypi.org.               0       IN      A       151.101.0.223
pypi.org.               0       IN      A       151.101.64.223
pypi.org.               0       IN      A       151.101.128.223
pypi.org.               0       IN      A       151.101.192.223
ns-96.awsdns-12.com.    0       IN      A       205.251.192.96
ns-897.awsdns-48.net.   0       IN      A       205.251.195.129
ns-1264.awsdns-30.org.  0       IN      A       205.251.196.240
ns-1702.awsdns-20.co.uk. 0      IN      A       205.251.198.166

;; Query time: 186 msec
;; SERVER: 172.29.112.1#53(172.29.112.1)
;; WHEN: Wed Aug 05 18:54:49 +05 2020
;; MSG SIZE  rcvd: 245
```

```shell
dig pypi.org AAAA
; <<>> DiG 9.10.3-P4-Ubuntu <<>> pypi.org AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 20341
;; flags: qr rd ad; QUERY: 1, ANSWER: 8, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;pypi.org.                      IN      AAAA

;; ANSWER SECTION:
pypi.org.               0       IN      AAAA    2a04:4e42:200::223
pypi.org.               0       IN      AAAA    2a04:4e42:400::223
pypi.org.               0       IN      AAAA    2a04:4e42:600::223
pypi.org.               0       IN      AAAA    2a04:4e42::223
ns-96.awsdns-12.com.    0       IN      A       205.251.192.96
ns-897.awsdns-48.net.   0       IN      A       205.251.195.129
ns-1264.awsdns-30.org.  0       IN      A       205.251.196.240
ns-1702.awsdns-20.co.uk. 0      IN      A       205.251.198.166

;; Query time: 203 msec
;; SERVER: 172.29.112.1#53(172.29.112.1)
;; WHEN: Wed Aug 05 18:55:19 +05 2020
;; MSG SIZE  rcvd: 293
```

```shell
dig files.pythonhosted.org A

; <<>> DiG 9.10.3-P4-Ubuntu <<>> files.pythonhosted.org A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25522
;; flags: qr rd ad; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;files.pythonhosted.org.                IN      A

;; ANSWER SECTION:
files.pythonhosted.org. 0       IN      CNAME   dualstack.r.ssl.global.fastly.net.
dualstack.r.ssl.global.fastly.net. 0 IN A       151.101.249.63
ns1.fastly.net.         0       IN      A       23.235.32.32
ns2.fastly.net.         0       IN      A       104.156.80.32
ns3.fastly.net.         0       IN      A       23.235.36.32
ns4.fastly.net.         0       IN      A       104.156.84.32

;; Query time: 199 msec
;; SERVER: 172.29.112.1#53(172.29.112.1)
;; WHEN: Wed Aug 05 18:55:41 +05 2020
;; MSG SIZE  rcvd: 278
```

```shell
dig files.pythonhosted.org AAAA
; <<>> DiG 9.10.3-P4-Ubuntu <<>> files.pythonhosted.org AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21592
;; flags: qr rd ad; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;files.pythonhosted.org.                IN      AAAA

;; ANSWER SECTION:
files.pythonhosted.org. 0       IN      CNAME   dualstack.r.ssl.global.fastly.net.
dualstack.r.ssl.global.fastly.net. 0 IN AAAA    2a04:4e42:3b::319
ns1.fastly.net.         0       IN      A       23.235.32.32
ns2.fastly.net.         0       IN      A       104.156.80.32
ns3.fastly.net.         0       IN      A       23.235.36.32
ns4.fastly.net.         0       IN      A       104.156.84.32

;; Query time: 207 msec
;; SERVER: 172.29.112.1#53(172.29.112.1)
;; WHEN: Wed Aug 05 18:55:59 +05 2020
;; MSG SIZE  rcvd: 290
```

#### IPv4

```shell
traceroute pypi.org
traceroute to pypi.org (151.101.128.223), 30 hops max, 60 byte packets
 1  DESKTOP-N7LIBN7.mshome.net (172.29.112.1)  0.413 ms  0.431 ms  0.419 ms
 2  10.30.0.17 (10.30.0.17)  14.908 ms  15.306 ms  13.719 ms
 3  192.168.52.6 (192.168.52.6)  33.949 ms  18.579 ms  38.267 ms
 4  91.218.162.145 (91.218.162.145)  34.548 ms  34.550 ms  39.630 ms
 5  91.185.23.34 (91.185.23.34)  28.577 ms  29.089 ms  87.160 ms
 6  10.40.30.10 (10.40.30.10)  57.052 ms  100.749 ms  98.642 ms
 7  10.40.30.9 (10.40.30.9)  98.851 ms  88.584 ms  54.017 ms
 8  ae5-571.RT.INT.STV.RU.retn.net (87.245.238.38)  54.051 ms  48.195 ms  53.937 ms
 9  ae3-8.RT.TC2.AMS.NL.retn.net (87.245.233.17)  97.408 ms  98.048 ms  98.416 ms
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

```shell
traceroute files.pythonhosted.org
traceroute to files.pythonhosted.org (151.101.249.63), 30 hops max, 60 byte packets
 1  DESKTOP-N7LIBN7.mshome.net (172.29.112.1)  0.171 ms  0.148 ms  0.369 ms
 2  10.30.0.17 (10.30.0.17)  65.282 ms  64.756 ms  65.264 ms
 3  192.168.52.6 (192.168.52.6)  67.818 ms  68.217 ms  68.212 ms
 4  91.218.162.145 (91.218.162.145)  68.193 ms * *
 5  * 91.185.23.34 (91.185.23.34)  77.045 ms *
 6  10.40.30.10 (10.40.30.10)  91.877 ms  91.148 ms  91.121 ms
 7  10.40.30.9 (10.40.30.9)  91.669 ms  98.417 ms  47.204 ms
 8  ae5-571.RT.INT.STV.RU.retn.net (87.245.238.38)  57.528 ms  67.417 ms  116.498 ms
 9  ae0-8.RT.TLX.NYC.US.retn.net (87.245.233.114)  188.527 ms  181.085 ms  188.513 ms
10  nyk-b6-link.telia.net (195.12.255.246)  208.425 ms  208.374 ms  208.403 ms
11  nyk-bb3-link.telia.net (62.115.125.62)  223.126 ms *  224.515 ms
12  * * *
13  * * rest-b2-link.telia.net (62.115.123.41)  223.065 ms
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

#### IPv6 (If available)

```shell
traceroute6 pypi.org
connect: Network is unreachable
```

```shell
traceroute6 files.pythonhosted.org
connect: Network is unreachable
```

#### IPv4

```shell
curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json
*   Trying 151.101.128.223...
* Connected to pypi.org (151.101.128.223) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
```
I'm not sure if this command should finish but it's hanging after * ALPN, offering http/1.1

```shell
curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
*   Trying 151.101.249.63...
* Connected to files.pythonhosted.org (151.101.249.63) port 443 (#0)
* found 148 certificates in /etc/ssl/certs/ca-certificates.crt
* found 592 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
```
I'm not sure if this command should finish but it's hanging after * ALPN, offering http/1.1

#### IPv6 (If available)

```shell
curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json
*   Trying 2a04:4e42:600::223...
* Immediate connect fail for 2a04:4e42:600::223: Network is unreachable
*   Trying 2a04:4e42::223...
* Immediate connect fail for 2a04:4e42::223: Network is unreachable
*   Trying 2a04:4e42:200::223...
* Immediate connect fail for 2a04:4e42:200::223: Network is unreachable
*   Trying 2a04:4e42:400::223...
* Immediate connect fail for 2a04:4e42:400::223: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

```shell
curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz
*   Trying 2a04:4e42:3b::319...
* Immediate connect fail for 2a04:4e42:3b::319: Network is unreachable
* Closing connection 0
curl: (7) Couldn't connect to server
```

#### IPv4

```shell
echo -n | openssl s_client -4 -connect pypi.org:443
CONNECTED(00000003)
```
Without -4 this option is unknown in my system

```shell
echo -n | openssl s_client -4 -connect files.pythonhosted.org:443
CONNECTED(00000003)
```
Without -4 this option is unknown in my system

#### IPv6 (If available)

```shell
echo -n | openssl s_client -6 -connect pypi.org:443
CONNECTED(00000003)
```

```shell
echo -n | openssl s_client -6 -connect files.pythonhosted.org:443
CONNECTED(00000003)
```

**Comment by di** [comment]
Can you show us the `pip install` command that is failing as well?

**Comment by daler-rahimov** [comment]
```shell
$ pip install pytest -vvv
Using pip 20.2 from /home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip (python 3.5)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-wa30xejm
Created temporary directory: /tmp/pip-req-tracker-_xipmim7
Initialized build tracking at /tmp/pip-req-tracker-_xipmim7
Created build tracker: /tmp/pip-req-tracker-_xipmim7
Entered build tracker: /tmp/pip-req-tracker-_xipmim7
Created temporary directory: /tmp/pip-install-zltmrt9d
1 location(s) to search for versions of pytest:
* https://pypi.org/simple/pytest/
Fetching project page and analyzing links: https://pypi.org/simple/pytest/
Getting page https://pypi.org/simple/pytest/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pytest/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/pytest/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytest/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/pytest/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytest/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/pytest/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytest/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/pytest/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytest/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/pytest/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/pytest/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/pytest/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pytest/ (Caused by ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)) - skipping
Given no hashes to check 0 links for project 'pytest': discarding no candidates
ERROR: Could not find a version that satisfies the requirement pytest (from versions: none)
ERROR: No matching distribution found for pytest
Exception information:
Traceback (most recent call last):
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for pytest
Removed build tracker: '/tmp/pip-req-tracker-_xipmim7'
```

```shell
$ pip install retrying==1.3.3 -vvv
Using pip 20.2 from /home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip (python 3.5)
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-5vhcfxe0
Created temporary directory: /tmp/pip-req-tracker-m5l072i5
Initialized build tracking at /tmp/pip-req-tracker-m5l072i5
Created build tracker: /tmp/pip-req-tracker-m5l072i5
Entered build tracker: /tmp/pip-req-tracker-m5l072i5
Created temporary directory: /tmp/pip-install-coct7aw_
1 location(s) to search for versions of retrying:
* https://pypi.org/simple/retrying/
Fetching project page and analyzing links: https://pypi.org/simple/retrying/
Getting page https://pypi.org/simple/retrying/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/retrying/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/retrying/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/retrying/ Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/retrying/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/retrying/ Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/retrying/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/retrying/ Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/retrying/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/retrying/ Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/retrying/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)': /simple/retrying/ Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/retrying/: connection error: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/retrying/ (Caused by ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)",)) - skipping
Given no hashes to check 0 links for project 'retrying': discarding no candidates
ERROR: Could not find a version that satisfies the requirement retrying==1.3.3 (from versions: none)
ERROR: No matching distribution found for retrying==1.3.3
Exception information:
Traceback (most recent call last):
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/home/daler/projects-local/lpav2/lpa-web/venv_py3/lib/python3.5/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    req)
pip._internal.exceptions.DistributionNotFound: No matching distribution found for retrying==1.3.3
Removed build tracker: '/tmp/pip-req-tracker-m5l072i5'
```

**Comment by daler-rahimov** [comment]
Any news on this issue or any workarounds. It's taking too much time to create wheelhouse on another machine every time I need to install anything.

**Comment by di** [comment]
Your `curl` command is definitely hanging at the point where it attempts to verify the certificate. Here's what I would expect to see instead:

```
$ curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json
*   Trying 151.101.64.223...
* TCP_NODELAY set
* Connected to pypi.org (151.101.64.223) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: businessCategory=Private Organization; jurisdictionCountryName=US; jurisdictionStateOrProvinceName=Delaware; serialNumber=3359300; C=US; ST=New Hampshire; L=Wolfeboro; O=Python Software Foundation; CN=www.python.org
*  start date: Sep 18 00:00:00 2018 GMT
*  expire date: Oct 14 12:00:00 2020 GMT
*  subjectAltName: host "pypi.org" matched cert's "pypi.org"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 Extended Validation Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f90b4808200)
> HEAD /pypi/pip/json HTTP/2
> Host: pypi.org
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
HTTP/2 200
< access-control-allow-headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
access-control-allow-headers: Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since
< access-control-allow-methods: GET
access-control-allow-methods: GET
< access-control-allow-origin: *
access-control-allow-origin: *
< access-control-expose-headers: X-PyPI-Last-Serial
access-control-expose-headers: X-PyPI-Last-Serial
< access-control-max-age: 86400
access-control-max-age: 86400
< cache-control: max-age=900, public
cache-control: max-age=900, public
< content-security-policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ *.fastly-insights.com sentry.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com https://cdn.ravenjs.com; style-src 'self' fonts.googleapis.com; worker-src *.fastly-insights.com
content-security-policy: base-uri 'self'; block-all-mixed-content; connect-src 'self' https://api.github.com/repos/ *.fastly-insights.com sentry.io https://api.pwnedpasswords.com https://2p66nmmycsj3.statuspage.io; default-src 'none'; font-src 'self' fonts.gstatic.com; form-action 'self'; frame-ancestors 'none'; frame-src 'none'; img-src 'self' https://warehouse-camo.ingress.cmh1.psfhosted.org/ www.google-analytics.com *.fastly-insights.com; script-src 'self' www.googletagmanager.com www.google-analytics.com *.fastly-insights.com https://cdn.ravenjs.com; style-src 'self' fonts.googleapis.com; worker-src *.fastly-insights.com
< content-type: application/json
content-type: application/json
< etag: "T/GfZwCU3HwS/rngN0fUZg"
etag: "T/GfZwCU3HwS/rngN0fUZg"
< referrer-policy: origin-when-cross-origin
referrer-policy: origin-when-cross-origin
< server: nginx/1.13.9
server: nginx/1.13.9
< x-pypi-last-serial: 7878779
x-pypi-last-serial: 7878779
< accept-ranges: bytes
accept-ranges: bytes
< date: Mon, 10 Aug 2020 15:36:21 GMT
date: Mon, 10 Aug 2020 15:36:21 GMT
< x-served-by: cache-bwi5133-BWI, cache-dfw18640-DFW
x-served-by: cache-bwi5133-BWI, cache-dfw18640-DFW
< x-cache: HIT, HIT
x-cache: HIT, HIT
< x-cache-hits: 7, 2
x-cache-hits: 7, 2
< x-timer: S1597073781.038235,VS0,VE0
x-timer: S1597073781.038235,VS0,VE0
< vary: Accept-Encoding, Accept-Encoding
vary: Accept-Encoding, Accept-Encoding
< strict-transport-security: max-age=31536000; includeSubDomains; preload
strict-transport-security: max-age=31536000; includeSubDomains; preload
< x-frame-options: deny
x-frame-options: deny
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-permitted-cross-domain-policies: none
x-permitted-cross-domain-policies: none
< content-length: 102581
content-length: 102581

<
* Connection #0 to host pypi.org left intact
* Closing connection 0
```

This is likely an issue with your local certificate bundle or TLS/SSL library.

Can you show us the result of `openssl s_client -showcerts -connect pypi.org:443`?

**Comment by daler-rahimov** [comment]
```shell
openssl s_client -showcerts -connect pypi.org:443
CONNECTED(00000003)
```
It says "CONNECTED" and hangs.

I don't think it's because of SSL. I did try a different virtual machine on the same network and I'm getting the same results. It looks like it's **related somehow to my Internet provider**. I tried **different network provider** (a cellular network) and everything is working just fine. 

I'll close this issues since I got a workaround and probably this is rare case

**Comment by om2c0de** [comment]
I've fixed this issue on my server by following setup:

 ~/.pip/pip.conf on ubuntu machine with content below

[global]
trusted-host = pypi.org files.pythonhosted.org

[install]
timeout = 100

Seems like other "more trusted" hosts fine for some providers and now in works great.
More info in doc https://pip.pypa.io/en/stable/topics/configuration/#pip-config-file
