### ISSUE TITLE
pip install -r requirements.txt failed, none packages installed?

### ISSUE THREAD

**Issue by zchrissirhcz** [pypa/pypi-support#549]
Hi,

I've just write up a requirements.txt for several lines, and the last line with a typo, other lines correct. Once execute `pip install -r requirements.txt`, it report failed. After fixing that typo, and re-run `pip install -r requirements.txt`, I found it **none packages was installed, and all packages have to be downloaded and installed again**. Why is this? What I expected is, only the package with typo shouldn't be installed, but other packages should be installed.

Example requirements.txt:
```
cython
tensorflow-gpu==1.15
opencv-python
onnxruntime-gpu==1.4.0
onnx==1.7.0
torhc==1.6.0   # this is the typo, since there is no "torhc", and it should be "torch"
```

Note: the pip version is:
pip 20.2.2 from /opt/miniconda/lib/python3.7/site-packages/pip (python 3.7)

Platform is: ubuntu 16.04

**Comment by di** [comment]
Can you show us the output from the `pip install` command?

**Comment by zchrissirhcz** [comment]
Hi, @di I've tried again on my another computer, and this time it uses cached files. I think it might be my fault that I didn't see that output message carefully. So sorry.

**Comment by zchrissirhcz** [comment]
The output message is:

```
(base) home% pip install -r requirements.txt
Looking in indexes: https://pypi.doubanio.com/simple
Requirement already satisfied: cython in /home/zz/soft/miniconda3/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.29.21)
Collecting tensorflow-gpu
  Using cached https://pypi.doubanio.com/packages/01/3a/672b3b3171a15d4929ffc5f53a0b1e66f614b0193b70d590d7d99aba55af/tensorflow_gpu-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (320.5 MB)
Requirement already satisfied: opencv-python in /home/zz/soft/miniconda3/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (4.3.0.36)
Collecting onnxruntime-gpu==1.4.0
  Using cached https://pypi.doubanio.com/packages/e4/ce/bdb5ee1bff36aa63bb2d7fbcaffe77583d5b3f38f9dee326f41c95716f22/onnxruntime_gpu-1.4.0-cp38-cp38-manylinux2010_x86_64.whl (25.4 MB)
Collecting onnx==1.7.0
  Using cached https://pypi.doubanio.com/packages/aa/4a/4d84b43473cf4b89b2b1c214252f2a2ddb50354a86541d0733aa739d2921/onnx-1.7.0-cp38-cp38-manylinux1_x86_64.whl (7.4 MB)
Collecting torch==1.6.0
  Downloading https://pypi.doubanio.com/packages/8c/5d/faf0d8ac260c7f1eda7d063001c137da5223be1c137658384d2d45dcd0d5/torch-1.6.0-cp38-cp38-manylinux1_x86_64.whl (748.8 MB)
     |████████████████████████████████| 748.8 MB 34 kB/s

**Comment by di** [comment]
That looks incomplete, is there more to it?

**Comment by zchrissirhcz** [comment]
```
(base) home% cat requirements.txt 
cython
tensorflow-gpu
opencv-python
onnxruntime-gpu==1.4.0
onnx==1.7.0
torhc==1.6.0
(base) home% pip uninstall -r requirements.txt 
WARNING: Skipping cython as it is not installed.
WARNING: Skipping tensorflow-gpu as it is not installed.
WARNING: Skipping opencv-python as it is not installed.
WARNING: Skipping onnxruntime-gpu as it is not installed.
WARNING: Skipping onnx as it is not installed.
WARNING: Skipping torhc as it is not installed.
(base) home% pip --version
pip 20.0.2 from /home/zz/soft/miniconda3/lib/python3.8/site-packages/pip (python 3.8)

(base) home% pip install -r requirements.txt
Looking in indexes: https://pypi.doubanio.com/simple
Collecting cython
  Downloading https://pypi.doubanio.com/packages/9f/05/959e78f2aeade1c9e85a7adc4c376f454ecaeb4cb6b079ca7a85684b69c1/Cython-0.29.21-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Collecting tensorflow-gpu
  Using cached https://pypi.doubanio.com/packages/01/3a/672b3b3171a15d4929ffc5f53a0b1e66f614b0193b70d590d7d99aba55af/tensorflow_gpu-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (320.5 MB)
Collecting opencv-python
  Downloading https://pypi.doubanio.com/packages/12/e3/beea1247e42101c6beeb3487fca4e15f45e916f34ebe25aafffbf255c54b/opencv_python-4.4.0.40-cp38-cp38-manylinux2014_x86_64.whl (49.4 MB)
Collecting onnxruntime-gpu==1.4.0
  Using cached https://pypi.doubanio.com/packages/e4/ce/bdb5ee1bff36aa63bb2d7fbcaffe77583d5b3f38f9dee326f41c95716f22/onnxruntime_gpu-1.4.0-cp38-cp38-manylinux2010_x86_64.whl (25.4 MB)
Collecting onnx==1.7.0
  Using cached https://pypi.doubanio.com/packages/aa/4a/4d84b43473cf4b89b2b1c214252f2a2ddb50354a86541d0733aa739d2921/onnx-1.7.0-cp38-cp38-manylinux1_x86_64.whl (7.4 MB)
ERROR: Could not find a version that satisfies the requirement torhc==1.6.0 (from -r requirements.txt (line 6)) (from versions: none)
ERROR: No matching distribution found for torhc==1.6.0 (from -r requirements.txt (line 6))

(base) home% python 
Python 3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cython'
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'cv2'
>>> import onnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'onnx'
>>> import onnxruntime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'onnxruntime'
```

**Comment by pradyunsg** [comment]
Closing this out, since this was a user-error and pip was aborting early.
