### ISSUE TITLE
Publishing with Poetry/Twine is giving a 403 "invalid macaroon!r" error

### ISSUE THREAD

**Issue by shughes-uk** [pypa/pypi-support#618]
Trying to publish my package, which worked fine this morning suddenly is giving this error. I did some debugging and got the underlying HTML response body.

I tried using a fresh token with no joy. I'm a little suspicious as it has what looks like an unformatted f string in the response.

## Version info
Poetry 1.0.10
Twine 3.2.0

url `https://upload.pypi.org/legacy/`
```html
<html>
 <head>
  <title>403 Invalid API Token: invalid macaroon!r</title>
 </head>
 <body>
  <h1>403 Invalid API Token: invalid macaroon!r</h1>
  Access was denied to this resource.<br/><br/>
Invalid API Token: invalid macaroon!r


 </body>
</html>
```

```shell
POETRY_HTTP_BASIC_PYPI_USERNAME=__token__ POETRY_HTTP_BASIC_PYPI_PASSWORD=<PYPI_TOKEN_REMOVED> poetry publish --build -vv    
Skipping virtualenv creation, as specified in config file.
Building nomnomdata-tools-engine (0.14.7)
 - Building sdist
 - Adding: nomnomdata/tools/engine/__init__.py
 - Adding: nomnomdata/tools/engine/cli.py
 - Adding: nomnomdata/tools/engine/code_sql_types.py
 - Adding: nomnomdata/tools/engine/create_new.py
 - Adding: nomnomdata/tools/engine/deploy.py
 - Adding: nomnomdata/tools/engine/model_update.py
 - Adding: nomnomdata/tools/engine/model_validator.py
 - Adding: nomnomdata/tools/engine/template/Dockerfile
 - Adding: nomnomdata/tools/engine/template/main.py
 - Adding: nomnomdata/tools/engine/template/pkg/__init__.py
 - Adding: nomnomdata/tools/engine/template/pkg/executable.py
 - Adding: nomnomdata/tools/engine/template/pkg/tests/__init__.py
 - Adding: nomnomdata/tools/engine/template/pkg/tests/test_executable.py
 - Adding: nomnomdata/tools/engine/template/requirements.txt
 - Adding: nomnomdata/tools/engine/testpass.out
 - Adding: nomnomdata/tools/engine/util.py
 - Adding: pyproject.toml
 - Adding: LICENSE
 - Adding: README.md
 - Built nomnomdata-tools-engine-0.14.7.tar.gz

 - Building wheel
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/__init__.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/cli.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/code_sql_types.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/create_new.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/deploy.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/model_update.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/model_validator.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/Dockerfile
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/main.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/pkg/__init__.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/pkg/executable.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/pkg/tests/__init__.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/pkg/tests/test_executable.py
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/template/requirements.txt
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/testpass.out
 - Adding: /var/folders/d7/m_bhbkd56l336_z8bqtcq9240000gn/T/tmpcq5h__nf/nomnomdata-tools-engine-0.14.7/nomnomdata/tools/engine/util.py
 - Built nomnomdata_tools_engine-0.14.7-py3-none-any.whl

Publishing nomnomdata-tools-engine (0.14.7) to PyPI
 - Uploading nomnomdata-tools-engine-0.14.7.tar.gz 100%
https://upload.pypi.org/legacy/

[UploadError]
HTTP Error 403: Invalid API Token: invalid macaroon!r

Traceback (most recent call last):
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/poetry/console/commands/publish.py", line 81, in handle
    client_cert,
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/poetry/masonry/publishing/publisher.py", line 92, in publish
    client_cert=resolved_client_cert,
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/poetry/masonry/publishing/uploader.py", line 103, in upload
    self._upload(session, url)
  File "/Users/shughes/miniconda3/lib/python3.7/site-packages/poetry/masonry/publishing/uploader.py", line 198, in _upload
    raise UploadError(e) from e

```

**Comment by jamadden** [comment]
Thank you for the report. I believe you were seeing a short-lived bug (pypa/warehouse#8554) that is now fixed. If you try again this should be resolved.
