### ISSUE TITLE
Issue: PEP 541 Request: Smap

### ISSUE THREAD

**Issue by DriesSchaumont** [pypa/pypi-support#896]
**Project to be claimed**

`Smap`: https://pypi.org/project/Smap/

**Your PyPI username**

`dschaumont`: https://pypi.org/user/dschaumont/

**Reasons for the request**

This project has been abandoned.

**Maintenance or replacement?**

I would like to replace this package with https://gitlab.com/truttink/smap

**Contact and additional research**

I have tried to contact the project owner at stevedh@eecs.berkeley.edu, but I have not received an answer for over two weeks. Furthermore, the project discription just states 'UNKNOWN', and the latest release dates back from  Mar 9, 2013.
I tried to visit the url of the project as listed in setup.py (http://cs.berkeley.edu/~stevedh/smap2/), but is seems that the webpage does not exist anymore. The code repository (https://code.google.com/archive/p/smap-data/) does still exist, but it seems that there was also no activity over there as well. I seems that the installation procedure has not been updated for a while, because `pip install smap` did not seem to work, at least not for `python3.8` with `pip 21.0.1`. 
```
ERROR: Command errored out with exit status 1:
command: /.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ck6zhog5/smap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ck6zhog5/smap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ck6zhog5/smap/pip-egg-info
         cwd: /tmp/pip-install-ck6zhog5/smap/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ck6zhog5/smap/setup.py", line 36, in <module>
        modbus_module = Extension('smap.iface.modbus._TCPModbusClient',
      File "/.venv/lib/python3.8/site-packages/setuptools/extension.py", line 39, in __init__
        _Extension.__init__(self, name, sources, *args, **kw)
      File "/usr/lib/python3.8/distutils/extension.py", line 107, in __init__
        raise AssertionError("'sources' must be a list of strings")
    AssertionError: 'sources' must be a list of strings
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by DriesSchaumont** [comment]
Hi @thoyt
Judging by your profile name and picture, I think that you are also listed as a maintainer on https://pypi.org/project/Smap/. I tried to contact Stephen Dawson-Haggerty on the email address listed above, but I could not get into contact with him. I was wondering if you would object to the transfer of the name 'smap' to me?
Thanks in advance!

**Comment by DriesSchaumont** [comment]
Hi @stevedh, I tried to contact you using the email address above regarding a request to transfer the SMAP project on pypi to me. I was wondering if you would object to this request?

**Comment by yeraydiazdiaz** [comment]
Hello @DriesSchaumont, while the project does look abandoned although there seems to be [_some_ package downloads](https://pepy.tech/project/smap?versions=2.0.bcb1a7&versions=2.0.c8506e&versions=2.0.ecaeca&versions=2.0.524). Following given the number of releases and size of the project and following the policy for [transferring abandoned projects in PEP 541](https://www.python.org/dev/peps/pep-0541/#removal-of-an-abandoned-project) I'm inclined to reject this transfer.

I will close this issue now for house keeping but if other moderators feel differently we can reopen it.

**Comment by DriesSchaumont** [comment]
Hi @yeraydiazdiaz Thank you for taking you time to go over this request. I understand how it may _seem_ that is project has some package downloads, howver I would like to argue that it is actually us driving traffic to pypi. We make our project public somewhere last year, and since then people started accidently download the wrong package. I confirmed this by looking at the statistics using Google's BigQuery from last year and comparing them to the download statistics from this year. Given this, would you be able to reconsider this request?
