### ISSUE TITLE
AWS default setuptools incompatible with recent fastly changes to disable non-SNI TLS access

### ISSUE THREAD

**Issue by mdw123** [pypa/pypi-support#983]
### My Platform

Sorry, this report colors outside of the lines. I suspect you'll be interested and that Fastly will contact you on this issue (they said they would). Please contact me directly, I'm happy to share everything I know and all of the correspondence with Fastly and future correspondence with AWS. Let me know how I can help ensure that no one gets their production systems killed by this confluence of situations.

AWS elastic beanstalk platform version 2.9.19
setuptools ~27.x (yeah, I know)

### Fastly Debug

I contacted fastly last night as recent cert changes for pythonhosted.org caused my installs on beanstalk to fail [support request #355931]. The root cause was fastly disabling non-SNI traffic to files.pythonhosted.org and the ancient version of setuptools that AWS packages with their default beanstalk platform on Amazon Linux. 

I've reached out to AWS to update their beanstalk image [AWS case #8144447391]. 

Recommendation: deprecate pre-SNI setuptools before v36.8.0, to influence AWS to include a newer setuptools (and pip and wheel, for goodness sake).

pip install crash callstack:
```
Collecting fastdiff==0.2.0 (from -r /opt/python/ondeck/app/requirements.txt (line 50))
    Using cached https://files.pythonhosted.org/packages/8a/4f/9fa421ce5f9ec46dfb64b99d0f2f83354e3a905f9e0b44c6e78ed72b4e16/fastdiff-0.2.0.tar.gz
      ERROR: Complete output from command python setup.py egg_info:
      ERROR: Traceback (most recent call last):
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/package_index.py", line 747, in open_url
          return open_with_auth(url, self.opener)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/package_index.py", line 948, in _socket_timeout
          return func(*args, **kwargs)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/package_index.py", line 1067, in open_with_auth
          fp = opener(request)
        File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
          response = self._open(req, data)
        File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
          '_open', req)
        File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
          result = func(*args)
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/ssl_support.py", line 161, in https_open
          lambda host, **kw: VerifyingHTTPSConn(host, self.ca_bundle, **kw), req
        File "/usr/lib64/python3.6/urllib/request.py", line 1349, in do_open
          encode_chunked=req.has_header('Transfer-encoding'))
        File "/usr/lib64/python3.6/http/client.py", line 1287, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "/usr/lib64/python3.6/http/client.py", line 1333, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "/usr/lib64/python3.6/http/client.py", line 1282, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "/usr/lib64/python3.6/http/client.py", line 1042, in _send_output
          self.send(msg)
        File "/usr/lib64/python3.6/http/client.py", line 980, in send
          self.connect()
        File "/opt/python/run/venv/local/lib/python3.6/site-packages/setuptools/ssl_support.py", line 193, in connect
          match_hostname(self.sock.getpeercert(), actual_host)
        File "/usr/lib64/python3.6/ssl.py", line 327, in match_hostname
          % (hostname, ', '.join(map(repr, dnsnames))))
      ssl.CertificateError: hostname 'files.pythonhosted.org' doesn't match either of 'r.ssl.fastly.net', '*.catchpoint.com', '*.cnn.io', '*.dollarshaveclub.com', '*.eater.com', '*.fastly.$
```

correspondence with Fastly

```
Pawel Dudek (Fastly)

Mar 24, 2021, 12:04 AM PDT

Hello Matt,

Thank you for your clarification. Jeff already mentioned that the change done in our system was the culprit. I don't have knowledge about Amazon's setuptools but everything was related to files.pythonhosted.org and non-sni traffic. By default, we do NOT support non-sni requests.

As you are not our direct customer, I'm not able to share more details but we will work directly with our customer to find the best solution that not affects end-users. For now, we will keep our temporary fix.

Kind regards,
Pawel | Fastly
```

### DNS Resolution

```console (paste your output after the line with the dig command)
$ dig pypi.org A

```

```console (paste your output after the line with the dig command)
$ dig pypi.org AAAA

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org A

```

```console (paste your output after the line with the dig command)
$ dig files.pythonhosted.org AAAA

```

### Traceroutes / IPv4

```console (paste your output after the line with the traceroute command)
$ traceroute pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute files.pythonhosted.org

```

### Traceroutes / IPv6 (If available)

```console (paste your output after the line with the traceroute command)
$ traceroute6 pypi.org

```

```console (paste your output after the line with the traceroute command)
$ traceroute6 files.pythonhosted.org

```

### HTTPS Requests / IPv4

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://pypi.org/pypi/pip/json

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv4 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### HTTPS Requests / IPv6 (If available)

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://pypi.org/pypi/pip/json

```

```console (paste your output after the line with the curl command)
$ curl -vvv -I --ipv6 https://files.pythonhosted.org/packages/ae/e8/2340d46ecadb1692a1e455f13f75e596d4eab3d11a57446f08259dee8f02/pip-10.0.1.tar.gz

```

### TLS Debug / IPv4

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect pypi.org:443

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -4 -connect files.pythonhosted.org:443

```

### TLS Debug / IPv6 (If available)

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect pypi.org:443

```

```console (paste your output after the line with the openssl command)
$ echo -n | openssl s_client -6 -connect files.pythonhosted.org:443

```

### Code of Conduct

- [X] I agree to follow the PSF Code of Conduct

**Comment by mattclay** [comment]
See https://github.com/pypa/pypi-support/issues/978 and https://github.com/pypa/pypi-support/issues/974

**Comment by mdw123** [comment]
> See #978 and #974

Thanks @mattclay

**Comment by pradyunsg** [comment]
Closing as a duplicate.
